name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Or the specific Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Login to Firebase
        uses: actions/google-login@v1
        with:
          client_id: ${{ secrets.FIREBASE_CLIENT_ID }}
          client_secret: ${{ secrets.FIREBASE_CLIENT_SECRET }}
          scopes: "https://www.googleapis.com/auth/firebase.database https://www.googleapis.com/auth/firebase.messaging https://www.googleapis.com/auth/firebase.storage"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          authToken: ${{ steps.login-to-firebase.outputs.auth_token }}
          site: ${{ secrets.FIREBASE_SITE }} # Optional: If you have multiple sites
          public_dir: dist/your-angular-app # Replace with your build output directory
