name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Or the specific Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Configure Firebase CLI
        run: |
          echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} > serviceAccountKey.json
          firebase use --project ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase login:ci --no-localhost --token $(cat serviceAccountKey.json | jq -r '.private_key')

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          site: ${{ secrets.FIREBASE_SITE }} # Optional: If you have multiple sites
          public_dir: dist/your-angular-app # Replace with your build output directory
